export const FETCH_MOVIES_LOADING = 'FETCH_MOVIES_LOADING'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL'

export const FETCH_MOVIE_BY_ID_LOADING = 'FETCH_MOVIE_BY_ID_LOADING'
export const FETCH_MOVIE_BY_ID_SUCCESS = 'FETCH_MOVIE_BY_ID_SUCCESS'
export const FETCH_MOVIE_BY_ID_FAIL = 'FETCH_MOVIE_BY_ID_FAIL'
